/* eslint-disable @next/next/no-img-element */
import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { createScreenshot } from '../playwright'

export const getStaticProps: GetStaticProps = async () => {
  // Generate images during build and place them in /public.
  if (process.env.NODE_ENV !== 'development') {
    const promises = ['first', 'second', 'third'].map((post) => createScreenshot(post))
    await Promise.all(promises)
  }
  return { props: {} }
}

const styleApiLink = { fontFamily: 'monospace', fontSize: 24 }
const styleInlineCode = {
  fontFamily: 'monospace',
  background: 'lightgray',
  borderRadius: 5,
  padding: 3,
}

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>vercel-social-image</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <style>{`html,body {
  font-family: -apple-system, Segoe UI, Roboto, Helvetica Neue, sans-serif;
}`}</style>
      </Head>
      <main style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
        <h1 style={{}}>vercel-social-image</h1>
        <p>Demonstrates different ways to generate dynamic images using next deployed to vercel.</p>
        <h2>
          Rendered Dynamically from Canvas using{' '}
          <span style={styleInlineCode}>@napi-rs/canvas</span>
        </h2>
        <Link href="/api/canvas/canving.png">
          <a>
            <img width={600} height={319} src="/api/canvas/canving.png" alt="Canvas" />
          </a>
        </Link>
        <p style={styleApiLink}>/api/canvas/[name].png</p>
        <h2>
          Rendered Dynamically from SVG using <span style={styleInlineCode}>@resvg/resvg-js</span>
        </h2>
        <Link href="/api/svg/svging.png">
          <a>
            <img width={600} height={319} src="/api/svg/svging.png" alt="SVG" />
          </a>
        </Link>
        <p style={styleApiLink}>/api/svg/[name].png</p>
        <h2>
          Rendered During Build from HTML using{' '}
          <span style={styleInlineCode}>playwright-chromium</span>
        </h2>
        <Link href="/build-first.png">
          <a>
            <Image width={600} height={319} src="/build-first.png" alt="Playwright" />
          </a>
        </Link>
        <p style={styleApiLink}>[/public]/build-*.png</p>
      </main>
    </div>
  )
}

export default Home
